name: Docusaurus
on:
  push:
    branches:
      - master

jobs:
  docusaurus:
    name: Docusaurus
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      
      - name: Configure Git
        run: |
          git config --global user.name "ramilego4game@user.noreply.github.com"
          git config --global user.email "GitHub Action"
      
      - name: Docusaurus
        run: |
          echo "machine github.com login ramilego4game password ${GITHUB_TOKEN}" > ~/.netrc
          cd website && yarn install && GIT_USER=ramilego4game yarn run publish-gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}