name: Docusaurus
on:
  push:
    branches:
      - master

jobs:
  docusaurus:
    - name: Git checkout
      uses: actions/checkout@v1
    
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'
    
    - name: Configure Git
      run: |
        git config --global user.name "action@github.com"
        git config --global user.email "GitHub Action"
    
    - name: Docusaurus
      run: |
        echo "machine github.com login GitHub Action password ${GH_TOKEN}" > ~/.netrc
        cd website && yarn install && GIT_USER="GitHub Action" yarn run publish-gh-pages
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

