name: Docusaurus
on:
  push:
    branches:
      - master

jobs:
  docusaurus:
    name: Docusaurus
    runs-on: ubuntu-18.04
    steps:
      - name: Update APT
        run: sudo apt update
      
      - name: Install LuaJIT and LuaRocks
        run: sudo apt install luajit luarocks

      - name: Install required Lua modules
        run: sudo luarocks install luafilesystem
      
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Generate LIKO-12 documentation
        run: luajit ./lua_scripts/generate_peripherals.lua
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      
      - name: Configure Git
        run: |
          git config --global user.name "RamiLego4Game (GitHub Action)"
          git config --global user.email "ramilego4game@github.com"
      
      - name: Docusaurus
        run: |
          echo "machine github.com login ramilego4game password ${GITHUB_TOKEN}" > ~/.netrc
          cd website && yarn install && GIT_USER=ramilego4game yarn run publish-gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}